namespace MechanismKinematicsWinFormsMVP
{
    partial class MainForm
    {
        /// <summary>
        /// Required constructor variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Release all used resources.
        /// </summary>
        /// <param name="disposing">истинно, если управляемый ресурс должен быть удален; иначе ложно.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code automatically generated by Windows Form Designer

        /// <summary>
        /// Required method for constructor support - do not change
        /// contents of this method using the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.pictureBox = new System.Windows.Forms.PictureBox();
            this.menuStrip = new System.Windows.Forms.MenuStrip();
            this.DrawingToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.DrawToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ClearToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.MovementToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.StartToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.StopToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ParametersToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.GeometricToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.KinematicToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.TrajectoryToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.PointAToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.PointBToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ExitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.Timer = new System.Windows.Forms.Timer(this.components);
            this.ParametersPanel = new System.Windows.Forms.Panel();
            this.pictureBoxPointB = new System.Windows.Forms.PictureBox();
            this.pictureBoxPointA = new System.Windows.Forms.PictureBox();
            this.LabelRadiusTwo = new System.Windows.Forms.Label();
            this.LabelRadiusOne = new System.Windows.Forms.Label();
            this.LabelOmega = new System.Windows.Forms.Label();
            this.LabelBeforeRadiusTwo = new System.Windows.Forms.Label();
            this.LabelBeforeRadiusOne = new System.Windows.Forms.Label();
            this.PointB = new System.Windows.Forms.Label();
            this.PointA = new System.Windows.Forms.Label();
            this.LabelAngleSpeed = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).BeginInit();
            this.menuStrip.SuspendLayout();
            this.ParametersPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxPointB)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxPointA)).BeginInit();
            this.SuspendLayout();
            // 
            // pictureBox
            // 
            this.pictureBox.BackColor = System.Drawing.Color.White;
            this.pictureBox.Location = new System.Drawing.Point(56, 80);
            this.pictureBox.Name = "pictureBox";
            this.pictureBox.Size = new System.Drawing.Size(298, 226);
            this.pictureBox.TabIndex = 0;
            this.pictureBox.TabStop = false;
            this.pictureBox.Paint += new System.Windows.Forms.PaintEventHandler(this.PictureBox_Paint);
            // 
            // menuStrip
            // 
            this.menuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.DrawingToolStripMenuItem,
            this.MovementToolStripMenuItem,
            this.ParametersToolStripMenuItem,
            this.TrajectoryToolStripMenuItem,
            this.ExitToolStripMenuItem});
            this.menuStrip.Location = new System.Drawing.Point(0, 0);
            this.menuStrip.Name = "menuStrip";
            this.menuStrip.Size = new System.Drawing.Size(643, 24);
            this.menuStrip.TabIndex = 1;
            this.menuStrip.Text = "menuStrip1";
            // 
            // DrawingToolStripMenuItem
            // 
            this.DrawingToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.DrawToolStripMenuItem,
            this.ClearToolStripMenuItem});
            this.DrawingToolStripMenuItem.Name = "DrawingToolStripMenuItem";
            this.DrawingToolStripMenuItem.Size = new System.Drawing.Size(63, 20);
            this.DrawingToolStripMenuItem.Text = "Drawing";
            // 
            // DrawToolStripMenuItem
            // 
            this.DrawToolStripMenuItem.Name = "DrawToolStripMenuItem";
            this.DrawToolStripMenuItem.ShortcutKeys = System.Windows.Forms.Keys.Insert;
            this.DrawToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.DrawToolStripMenuItem.Text = "Draw";
            this.DrawToolStripMenuItem.Click += new System.EventHandler(this.DrawToolStripMenuItem_Click);
            // 
            // ClearToolStripMenuItem
            // 
            this.ClearToolStripMenuItem.Name = "ClearToolStripMenuItem";
            this.ClearToolStripMenuItem.ShortcutKeys = System.Windows.Forms.Keys.Delete;
            this.ClearToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.ClearToolStripMenuItem.Text = "Clear";
            this.ClearToolStripMenuItem.Click += new System.EventHandler(this.ClearToolStripMenuItem_Click);
            // 
            // MovementToolStripMenuItem
            // 
            this.MovementToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.StartToolStripMenuItem,
            this.StopToolStripMenuItem});
            this.MovementToolStripMenuItem.Name = "MovementToolStripMenuItem";
            this.MovementToolStripMenuItem.Size = new System.Drawing.Size(77, 20);
            this.MovementToolStripMenuItem.Text = "Movement";
            // 
            // StartToolStripMenuItem
            // 
            this.StartToolStripMenuItem.Name = "StartToolStripMenuItem";
            this.StartToolStripMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F4;
            this.StartToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.StartToolStripMenuItem.Text = "Start";
            this.StartToolStripMenuItem.Click += new System.EventHandler(this.StartToolStripMenuItem_Click);
            // 
            // StopToolStripMenuItem
            // 
            this.StopToolStripMenuItem.Name = "StopToolStripMenuItem";
            this.StopToolStripMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F3;
            this.StopToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.StopToolStripMenuItem.Text = "Stop";
            this.StopToolStripMenuItem.Click += new System.EventHandler(this.StopToolStripMenuItem_Click);
            // 
            // ParametersToolStripMenuItem
            // 
            this.ParametersToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.GeometricToolStripMenuItem,
            this.KinematicToolStripMenuItem});
            this.ParametersToolStripMenuItem.Name = "ParametersToolStripMenuItem";
            this.ParametersToolStripMenuItem.Size = new System.Drawing.Size(78, 20);
            this.ParametersToolStripMenuItem.Text = "Parameters";
            // 
            // GeometricToolStripMenuItem
            // 
            this.GeometricToolStripMenuItem.Name = "GeometricToolStripMenuItem";
            this.GeometricToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.GeometricToolStripMenuItem.Text = "Geometric";
            this.GeometricToolStripMenuItem.Click += new System.EventHandler(this.GeometricToolStripMenuItem_Click);
            // 
            // KinematicToolStripMenuItem
            // 
            this.KinematicToolStripMenuItem.Name = "KinematicToolStripMenuItem";
            this.KinematicToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.KinematicToolStripMenuItem.Text = "Kinematic";
            this.KinematicToolStripMenuItem.Click += new System.EventHandler(this.KinematicToolStripMenuItem_Click);
            // 
            // TrajectoryToolStripMenuItem
            // 
            this.TrajectoryToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.PointAToolStripMenuItem,
            this.PointBToolStripMenuItem});
            this.TrajectoryToolStripMenuItem.Name = "TrajectoryToolStripMenuItem";
            this.TrajectoryToolStripMenuItem.Size = new System.Drawing.Size(71, 20);
            this.TrajectoryToolStripMenuItem.Text = "Trajectory";
            // 
            // PointAToolStripMenuItem
            // 
            this.PointAToolStripMenuItem.Enabled = false;
            this.PointAToolStripMenuItem.Name = "PointAToolStripMenuItem";
            this.PointAToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.A)));
            this.PointAToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.PointAToolStripMenuItem.Text = "Point A";
            this.PointAToolStripMenuItem.Click += new System.EventHandler(this.PointAToolStripMenuItem_Click);
            // 
            // PointBToolStripMenuItem
            // 
            this.PointBToolStripMenuItem.Enabled = false;
            this.PointBToolStripMenuItem.Name = "PointBToolStripMenuItem";
            this.PointBToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.B)));
            this.PointBToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.PointBToolStripMenuItem.Text = "Point B";
            this.PointBToolStripMenuItem.Click += new System.EventHandler(this.PointBToolStripMenuItem_Click);
            // 
            // ExitToolStripMenuItem
            // 
            this.ExitToolStripMenuItem.Name = "ExitToolStripMenuItem";
            this.ExitToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.ExitToolStripMenuItem.Text = "Exit";
            this.ExitToolStripMenuItem.Click += new System.EventHandler(this.ExitToolStripMenuItem_Click);
            // 
            // Timer
            // 
            this.Timer.Tick += new System.EventHandler(this.Timer_Tick);
            // 
            // ParametersPanel
            // 
            this.ParametersPanel.Controls.Add(this.pictureBoxPointB);
            this.ParametersPanel.Controls.Add(this.pictureBoxPointA);
            this.ParametersPanel.Controls.Add(this.LabelRadiusTwo);
            this.ParametersPanel.Controls.Add(this.LabelRadiusOne);
            this.ParametersPanel.Controls.Add(this.LabelOmega);
            this.ParametersPanel.Controls.Add(this.LabelBeforeRadiusTwo);
            this.ParametersPanel.Controls.Add(this.LabelBeforeRadiusOne);
            this.ParametersPanel.Controls.Add(this.PointB);
            this.ParametersPanel.Controls.Add(this.PointA);
            this.ParametersPanel.Controls.Add(this.LabelAngleSpeed);
            this.ParametersPanel.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.ParametersPanel.Location = new System.Drawing.Point(0, 434);
            this.ParametersPanel.Name = "ParametersPanel";
            this.ParametersPanel.Size = new System.Drawing.Size(643, 88);
            this.ParametersPanel.TabIndex = 2;
            // 
            // pictureBoxPointB
            // 
            this.pictureBoxPointB.BackColor = System.Drawing.Color.Blue;
            this.pictureBoxPointB.Location = new System.Drawing.Point(187, 50);
            this.pictureBoxPointB.Name = "pictureBoxPointB";
            this.pictureBoxPointB.Size = new System.Drawing.Size(36, 26);
            this.pictureBoxPointB.TabIndex = 9;
            this.pictureBoxPointB.TabStop = false;
            // 
            // pictureBoxPointA
            // 
            this.pictureBoxPointA.BackColor = System.Drawing.Color.Red;
            this.pictureBoxPointA.Location = new System.Drawing.Point(68, 50);
            this.pictureBoxPointA.Name = "pictureBoxPointA";
            this.pictureBoxPointA.Size = new System.Drawing.Size(36, 26);
            this.pictureBoxPointA.TabIndex = 8;
            this.pictureBoxPointA.TabStop = false;
            // 
            // LabelRadiusTwo
            // 
            this.LabelRadiusTwo.AutoSize = true;
            this.LabelRadiusTwo.Location = new System.Drawing.Point(373, 16);
            this.LabelRadiusTwo.Name = "LabelRadiusTwo";
            this.LabelRadiusTwo.Size = new System.Drawing.Size(13, 13);
            this.LabelRadiusTwo.TabIndex = 7;
            this.LabelRadiusTwo.Text = "0";
            // 
            // LabelRadiusOne
            // 
            this.LabelRadiusOne.AutoSize = true;
            this.LabelRadiusOne.Location = new System.Drawing.Point(243, 16);
            this.LabelRadiusOne.Name = "LabelRadiusOne";
            this.LabelRadiusOne.Size = new System.Drawing.Size(13, 13);
            this.LabelRadiusOne.TabIndex = 6;
            this.LabelRadiusOne.Text = "0";
            // 
            // LabelOmega
            // 
            this.LabelOmega.AutoSize = true;
            this.LabelOmega.Location = new System.Drawing.Point(103, 16);
            this.LabelOmega.Name = "LabelOmega";
            this.LabelOmega.Size = new System.Drawing.Size(13, 13);
            this.LabelOmega.TabIndex = 5;
            this.LabelOmega.Text = "0";
            // 
            // LabelBeforeRadiusTwo
            // 
            this.LabelBeforeRadiusTwo.AutoSize = true;
            this.LabelBeforeRadiusTwo.Location = new System.Drawing.Point(309, 16);
            this.LabelBeforeRadiusTwo.Name = "LabelBeforeRadiusTwo";
            this.LabelBeforeRadiusTwo.Size = new System.Drawing.Size(55, 13);
            this.LabelBeforeRadiusTwo.TabIndex = 4;
            this.LabelBeforeRadiusTwo.Text = "Radius r2:";
            // 
            // LabelBeforeRadiusOne
            // 
            this.LabelBeforeRadiusOne.AutoSize = true;
            this.LabelBeforeRadiusOne.Location = new System.Drawing.Point(179, 16);
            this.LabelBeforeRadiusOne.Name = "LabelBeforeRadiusOne";
            this.LabelBeforeRadiusOne.Size = new System.Drawing.Size(55, 13);
            this.LabelBeforeRadiusOne.TabIndex = 3;
            this.LabelBeforeRadiusOne.Text = "Radius r1:";
            // 
            // PointB
            // 
            this.PointB.AutoSize = true;
            this.PointB.Location = new System.Drawing.Point(131, 55);
            this.PointB.Name = "PointB";
            this.PointB.Size = new System.Drawing.Size(44, 13);
            this.PointB.TabIndex = 2;
            this.PointB.Text = "Point B:";
            // 
            // PointA
            // 
            this.PointA.AutoSize = true;
            this.PointA.Location = new System.Drawing.Point(12, 55);
            this.PointA.Name = "PointA";
            this.PointA.Size = new System.Drawing.Size(44, 13);
            this.PointA.TabIndex = 1;
            this.PointA.Text = "Point A:";
            // 
            // LabelAngleSpeed
            // 
            this.LabelAngleSpeed.AutoSize = true;
            this.LabelAngleSpeed.Location = new System.Drawing.Point(12, 16);
            this.LabelAngleSpeed.Name = "LabelAngleSpeed";
            this.LabelAngleSpeed.Size = new System.Drawing.Size(85, 13);
            this.LabelAngleSpeed.TabIndex = 0;
            this.LabelAngleSpeed.Text = "Angular velocity:";
            // 
            // MainForm
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.ClientSize = new System.Drawing.Size(643, 522);
            this.Controls.Add(this.ParametersPanel);
            this.Controls.Add(this.pictureBox);
            this.Controls.Add(this.menuStrip);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MainMenuStrip = this.menuStrip;
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Mechanism Kinematics";
            this.Load += new System.EventHandler(this.MainForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).EndInit();
            this.menuStrip.ResumeLayout(false);
            this.menuStrip.PerformLayout();
            this.ParametersPanel.ResumeLayout(false);
            this.ParametersPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxPointB)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxPointA)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox pictureBox;
        private System.Windows.Forms.MenuStrip menuStrip;
        private System.Windows.Forms.ToolStripMenuItem DrawingToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem MovementToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem StartToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem StopToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ParametersToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem TrajectoryToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ExitToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem DrawToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ClearToolStripMenuItem;
        private System.Windows.Forms.Timer Timer;
        private System.Windows.Forms.ToolStripMenuItem PointAToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem PointBToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem GeometricToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem KinematicToolStripMenuItem;
        private System.Windows.Forms.Panel ParametersPanel;
        private System.Windows.Forms.Label PointB;
        private System.Windows.Forms.Label PointA;
        private System.Windows.Forms.Label LabelAngleSpeed;
        private System.Windows.Forms.Label LabelRadiusTwo;
        private System.Windows.Forms.Label LabelRadiusOne;
        private System.Windows.Forms.Label LabelOmega;
        private System.Windows.Forms.Label LabelBeforeRadiusTwo;
        private System.Windows.Forms.Label LabelBeforeRadiusOne;
        private System.Windows.Forms.PictureBox pictureBoxPointB;
        private System.Windows.Forms.PictureBox pictureBoxPointA;
    }
}

